//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.ResX {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SampleApp.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Form_BirthDate {
            get {
                return ResourceManager.GetString("Form.BirthDate", resourceCulture);
            }
        }
        
        internal static string Form_City {
            get {
                return ResourceManager.GetString("Form.City", resourceCulture);
            }
        }
        
        internal static string Form_Civility {
            get {
                return ResourceManager.GetString("Form.Civility", resourceCulture);
            }
        }
        
        internal static string Form_Email {
            get {
                return ResourceManager.GetString("Form.Email", resourceCulture);
            }
        }
        
        internal static string Form_FirstName {
            get {
                return ResourceManager.GetString("Form.FirstName", resourceCulture);
            }
        }
        
        internal static string Form_LastName {
            get {
                return ResourceManager.GetString("Form.LastName", resourceCulture);
            }
        }
        
        internal static string Form_Phone {
            get {
                return ResourceManager.GetString("Form.Phone", resourceCulture);
            }
        }
        
        internal static string Form_ZipCode {
            get {
                return ResourceManager.GetString("Form.ZipCode", resourceCulture);
            }
        }
        
        internal static string Error_Check {
            get {
                return ResourceManager.GetString("Error.Check", resourceCulture);
            }
        }
        
        internal static string Error_EmailMatch {
            get {
                return ResourceManager.GetString("Error.EmailMatch", resourceCulture);
            }
        }
        
        internal static string Error_Empty {
            get {
                return ResourceManager.GetString("Error.Empty", resourceCulture);
            }
        }
        
        internal static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error.InvalidEmail", resourceCulture);
            }
        }
        
        internal static string Error_MajorAge {
            get {
                return ResourceManager.GetString("Error.MajorAge", resourceCulture);
            }
        }
        
        internal static string SignIn_Email {
            get {
                return ResourceManager.GetString("SignIn.Email", resourceCulture);
            }
        }
        
        internal static string SignIn_NoAccount {
            get {
                return ResourceManager.GetString("SignIn.NoAccount", resourceCulture);
            }
        }
        
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn.Password", resourceCulture);
            }
        }
        
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn.SignIn", resourceCulture);
            }
        }
        
        internal static string Form_Already {
            get {
                return ResourceManager.GetString("Form.Already", resourceCulture);
            }
        }
        
        internal static string Form_EmailConfirm {
            get {
                return ResourceManager.GetString("Form.EmailConfirm", resourceCulture);
            }
        }
        
        internal static string Form_Man {
            get {
                return ResourceManager.GetString("Form.Man", resourceCulture);
            }
        }
        
        internal static string Form_Button {
            get {
                return ResourceManager.GetString("Form.Button", resourceCulture);
            }
        }
        
        internal static string Form_Woman {
            get {
                return ResourceManager.GetString("Form.Woman", resourceCulture);
            }
        }
        
        internal static string Form_English {
            get {
                return ResourceManager.GetString("Form.English", resourceCulture);
            }
        }
        
        internal static string Form_Spanish {
            get {
                return ResourceManager.GetString("Form.Spanish", resourceCulture);
            }
        }
        
        internal static string Form_Russian {
            get {
                return ResourceManager.GetString("Form.Russian", resourceCulture);
            }
        }
    }
}
